# Companion language packs for generate_droniq_geos.py (ro, hu, hr, si, cz, sk, pl)
# noqa: expects COPY dict in caller globals

COPY["ro"] = {
    "title": "Droniq™ — Dronă Ultra HD 8K cu GPS și Evitare a Obstacolelor | -60%",
    "meta_desc": "Droniq™: dronă Ultra HD 8K, ușor de zburat din prima zi, fără licență (C0 A1/A3). Retur GPS automat, senzori de obstacole, zoom 22x, 3 baterii pentru 2+ ore de zbor. Plata la livrare, transport gratuit 24/48h.",
    "og_title": "Droniq™ — Dronă Ultra HD 8K | -60%",
    "og_desc": "Ultra HD 8K, retur GPS automat, senzori de obstacole, fără licență. Plata la livrare.",
    "submitting": "Se trimite...",
    "cookie_text": "Folosim cookie-uri esențiale și de terți pentru a îmbunătăți experiența ta și pentru analize.",
    "cookie_accept": "Accept",
    "cookie_learn": "Află mai mult",
    "topbar": "🔥 REDUCERE 60% + TRANSPORT GRATUIT — PLATA LA LIVRARE 🔥",
    "rating": "<strong>4,8/5</strong> — pe baza a <strong>3.842+ recenzii verificate</strong>",
    "gift": "🎁 GRATUIT: 3 baterii + husă rigidă + elice de rezervă",
    "h1": 'Creează videoclipuri care impresionează pe toată lumea.<br>O singură dronă: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ este o <strong>dronă Ultra HD 8K</strong> ușor de zburat de la primul decolare — <strong>fără licență necesară</strong>. GPS cu retur automat, senzori inteligenți de obstacole, viteze de până la <strong>120 km/h</strong> și stocare extensibilă până la <strong>256 GB</strong> pentru ore de filmări de calitate cinematografică.",
    "alt_hero": "Kit complet Droniq™ dronă Ultra HD 8K",
    "cta": "DA, VREAU Droniq™ →",
    "cta_submit": "DA, VREAU Droniq™",
    "form_note": "🔒 Fără avans · Fără card · Plătești doar la livrare",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Video de calitate cinematografică și fotografii clare",
    "feat2_h": "GPS inteligent",
    "feat2_p": "Retur automat când scade semnalul sau bateria",
    "feat3_h": "Senzori de obstacole",
    "feat3_p": "Detectează și evită obstacolele din față",
    "feat4_h": "Plata la livrare",
    "feat4_p": "Convenabil, sigur, fără plată în avans",
    "countdown": "⏰ Reducerea de 60% expiră în",
    "hrs": "Ore",
    "min": "Min",
    "sec": "Sec",
    "stock_left": "Disponibilitate în depozit",
    "stock_right": "Doar 8 unități rămase",
    "live_tpl": "&lt;strong&gt;{n} persoane&lt;/strong&gt; privesc Droniq acum",
    "live_html": "<strong>36 persoane</strong> privesc Droniq acum",
    "order_h2": "Finalizează comanda",
    "order_p": "Completează formularul — echipa noastră te va contacta pentru a confirma fiecare detaliu.",
    "label_name": "Nume complet *",
    "err_name": "Introdu numele complet (cel puțin 3 caractere)",
    "label_phone": "Număr de telefon *",
    "err_phone": "Introdu un număr de telefon valid",
    "label_address": "Adresa de livrare *",
    "err_address": "Introdu o adresă completă (cel puțin 10 caractere)",
    "why1_eye": "01 — Filmări de calitate cinematografică",
    "why1_h3": "Video Ultra HD 8K — panorame și detalii îndepărtate într-o singură cadru",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">Zoom 22x</span><span class="tag">Unghi larg</span>',
    "why1_p": "Creează filme și fotografii cu aspect profesional. Panorame spectaculoase, detalii clare și priveliști aeriene impresionante transformă fiecare călătorie în amintiri pe care le vei revedea ani de zile. Camera <strong>Ultra HD 8K</strong>, obiectivul cu unghi larg și <strong>zoom-ul digital 22x</strong> te lasă să treci de la peisaje ample la detalii îndepărtate fără a pierde claritatea.",
    "why1_i": "Transformă fiecare călătorie în amintiri de calitate cinematografică.",
    "alt_desc1": "Cameră Droniq™ Ultra HD 8K cu zoom 22x",
    "why2_eye": "02 — Zboară în siguranță în orice situație",
    "why2_h3": "GPS inteligent, senzori de obstacole și Follow Me — liniște totală",
    "why2_tags": '<span class="tag">Retur GPS</span><span class="tag">Anticoliziune</span><span class="tag">Follow Me</span>',
    "why2_p": "AI ajută la detectarea obstacolelor, GPS urmărește constant poziția, iar dacă semnalul scade sau bateria se epuizează, Droniq™ <strong>revine automat la punctul de decolare</strong>. Decolare și aterizare automată și modul Follow Me fac fiecare zbor mai ușor și mai sigur — chiar dacă nu ai mai zburat o dronă.",
    "why2_i": "Zbori cu încredere — Droniq™ te protejează.",
    "aria_video": "Retur GPS automat și evitare obstacole Droniq™",
    "why3_eye": "03 — Gata din prima zi",
    "why3_h3": "Fără licență · 2+ ore de zbor · stabil până la vânt de 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 baterii</span><span class="tag">Vânt 38 km/h</span>',
    "why3_p": "Droniq™ respectă standardul <strong>C0 (A1/A3)</strong> — fără licență, certificate sau birocrație. Elicele din fibră de carbon și stabilizarea avansată păstrează imaginile clare chiar și la vânt de până la <strong>38 km/h</strong>. Kitul include <strong>3 baterii de mare capacitate</strong> pentru peste 2 ore de zbor total.",
    "why3_i": "Pornește-o, decolează și începe să filmezi azi.",
    "alt_desc3": "Zbor stabil Droniq™ până la vânt de 38 km/h cu 3 baterii",
    "compare_label": "De ce merită cu adevărat",
    "compare_h2": "Camera telefonului / dronă de bază vs Droniq™",
    "th_phone": "Telefon / dronă de bază",
    "td_price": "Preț",
    "td_price_other": "pentru echipament separat",
    "once": "o singură dată",
    "td_video": "Video",
    "td_video_other": "Calitate medie de telefon",
    "td_video_win": "Ultra HD 8K + zoom 22x",
    "td_safety": "Siguranță",
    "td_safety_other": "Doar manual — ușor de pierdut",
    "td_safety_win": "Retur GPS + senzori de obstacole",
    "td_flight": "Timp de zbor",
    "td_flight_other": "Adesea sub 20 de minute",
    "td_flight_win": "2+ ore cu 3 baterii",
    "td_license": "Licență",
    "td_license_other": "Adesea necesară",
    "td_license_win": "C0 — fără licență",
    "td_warranty": "Garanție",
    "td_warranty_other": "Variază",
    "td_warranty_win": "24 luni + 30 zile retur",
    "t_eye": "⭐ 4,8/5 · Achiziție verificată · Recenzii moderate",
    "t_h2": "Mii de clienți recomandă Droniq™",
    "t1_h": "Perfect pentru începători",
    "t1_p": "«A fost prima mea dronă și mi-era teamă că va fi greu. În câteva minute eram în aer. Decolarea și aterizarea automate ușurează zborul, iar GPS-ul îmi dă liniște pe tot parcursul. Aș recomanda-o chiar și celor care nu au zburat niciodată.»",
    "t1_verified": "Achiziție verificată",
    "t2_h": "Calitatea filmărilor m-a uimit",
    "t2_p": "«Am luat-o într-o excursie la munte și imaginile au ieșit spectaculoase. Chiar și pe vânt mai puternic a rămas stabilă, iar videoclipurile erau clare și fluide. La acest preț a fost o achiziție fantastică.»",
    "t3_h": "Kit complet, retur automat",
    "t3_p": "«Setul a ajuns complet — trei baterii, elice de rezervă, totul pentru a începe. Funcția de retur automat m-a convins cel mai mult: dacă scade semnalul sau se termină bateria, se întoarce singură. Acum zbor mult mai calm.»",
    "kit_eye": "Ce este în cutie",
    "kit_h2": "📦 Kit Droniq™ complet gata de zbor",
    "alt_kit": "Kit complet dronă Droniq™",
    "kit1": "<strong>1× Dronă profesională Droniq™</strong> — Ultra HD 8K, GPS, senzori de obstacole",
    "kit2": "<strong>3× Baterii de mare capacitate</strong> — peste 2 ore de zbor total",
    "kit3": "1× Telecomandă inteligentă",
    "kit4": "1× Încărcător rapid (~30 minute)",
    "kit5": "6× Elice de rezervă",
    "kit6": "1× Husă rigidă de transport",
    "kit7": "Manual de utilizare + garanție 24 luni",
    "kit8": "Transport gratuit 24/48 h",
    "faq_eye": "Întrebări frecvente",
    "faq_h2": "Răspunsuri chiar aici",
    "faq": [
        ("Cum comand?", "Completează formularul cu numele, telefonul și adresa. Echipa noastră te va contacta, va răspunde la întrebări și va confirma detaliile de livrare."),
        ("Pot plăti la livrare?", "Da. Pentru comoditate și siguranță poți plăti la livrare: când ajunge produsul, plătești curierului. Nu sunt necesare date de card."),
        ("Este ușor de zburat pentru începători?", "Da. Droniq™ este concepută pentru cei care nu au mai zburat o dronă. Decolarea și aterizarea sunt automate, comenzile sunt intuitive, iar AI ajută la un zbor stabil și sigur de la prima utilizare."),
        ("Am nevoie de licență sau certificat?", "Nu. Droniq™ respectă standardul <strong>C0</strong> în categoria A1/A3 și poate fi folosită fără licență, certificate sau birocrație complicată."),
        ("Ce calitate video și foto oferă?", "Droniq™ înregistrează în <strong>Ultra HD 8K</strong> și face fotografii excepțional de clare. Obiectivul cu unghi larg și zoom-ul digital 22x permit trecerea fluidă de la panorame la detalii îndepărtate."),
        ("Ce se întâmplă dacă drona pierde semnalul sau scade bateria?", "Datorită modulului GPS integrat, Droniq™ revine automat la punctul de decolare dacă se pierde semnalul sau bateria este scăzută."),
        ("Ce se întâmplă dacă nu sunt mulțumit?", "Ai <strong>30 de zile</strong> de la livrare pentru retur sau schimb, plus garanție de 24 de luni pentru defecte de fabricație și suport clienți."),
        ("Cât costă transportul și cât durează?", "Transportul este <strong>gratuit</strong>. Procesăm comenzile în 24 de ore; curierul ajunge de obicei în 24/48 de ore lucrătoare."),
    ],
    "footer_blurb": "Produse utile de zi cu zi, livrare în 24–48 de ore cu plata la livrare.",
    "footer_info": "Informații",
    "footer_about": "Despre noi",
    "footer_contact_us": "Contactează-ne",
    "footer_privacy": "Politica de Confidențialitate",
    "footer_terms": "Termeni și Condiții",
    "footer_cookie": "Politica Cookie-uri",
    "footer_shipping": "Politica de Livrare",
    "footer_refund": "Politica de Returnare",
    "footer_contact": "Contact",
    "footer_rights": "Toate drepturile rezervate",
    "ty_title": "Comandă primită — Te rugăm să răspunzi la apelul de confirmare | Droniq™",
    "ty_meta": "Comanda ta Droniq™ a fost înregistrată. Un ultim pas: răspunde la apelul de confirmare de la operatorul nostru.",
    "ty_h1": "Comanda ta a fost înregistrată cu succes!",
    "ty_sub": "Excelent — comanda ta este în procesare. Mai lipsește doar <strong>un ultim pas</strong> pentru a o finaliza și a începe livrarea.",
    "ty_img_alt": "Echipa Crazy Marketing la lucru: call center COD și logistică",
    "ty_eye": "👇 Ce trebuie să faci acum",
    "ty_action_h": "📞 Răspunde la apelul de confirmare",
    "ty_action_body": "Unul dintre operatorii noștri te va contacta <strong>în următoarele ore</strong> pentru a confirma comanda.",
    "ty_warn": "Dacă nu răspunzi la apel, comanda va fi anulată automat.",
    "ty_hours_h": "🕒 Program de contact",
    "ty_hours": "<strong>Luni – Sâmbătă</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Ce urmează",
    "ty_s1": "Răspunde la apel și <strong>confirmă datele</strong>",
    "ty_s2": "Comanda ta va fi expediată în <strong>24–48 de ore</strong>",
    "ty_s3": "Livrare la domiciliu și <strong>plata la livrare</strong>",
    "ty_b1": "🔒 Plata la livrare",
    "ty_b2": "🛡️ Garanție 2 ani",
    "ty_b3": "🔐 Protecție SSL",
    "ty_rights": "Toate drepturile rezervate.",
    "index_link": "Mergi la landing-ul Droniq™",
}

COPY["hu"] = {
    "title": "Droniq™ — Ultra HD 8K drón GPS-sel és akadályelkerüléssel | -60%",
    "meta_desc": "Droniq™: Ultra HD 8K drón, könnyen vezethető az első naptól, engedély nélkül (C0 A1/A3). GPS automatikus visszatérés, akadályérzékelők, 22x zoom, 3 akkumulátor 2+ óra repüléshez. Utánvét, ingyenes szállítás 24/48h.",
    "og_title": "Droniq™ — Ultra HD 8K drón | -60%",
    "og_desc": "Ultra HD 8K, GPS automatikus visszatérés, akadályérzékelők, engedély nélkül. Utánvét.",
    "submitting": "Küldés...",
    "cookie_text": "Alapvető és harmadik féltől származó cookie-kat használunk a jobb élmény és az elemzés érdekében.",
    "cookie_accept": "Elfogadom",
    "cookie_learn": "Tudj meg többet",
    "topbar": "🔥 60% KEDVEZMÉNY + INGYENES SZÁLLÍTÁS — UTÁNVÉT 🔥",
    "rating": "<strong>4,8/5</strong> — <strong>3 842+ ellenőrzött</strong> értékelés alapján",
    "gift": "🎁 INGYEN: 3 akkumulátor + kemény tok + tartalék propeller",
    "h1": 'Készíts videókat, amelyek mindenkit elkápráztatnak.<br>Egy drón: <span class="hl">Droniq™</span>',
    "lead": "A Droniq™ egy <strong>Ultra HD 8K drón</strong>, amely az első felszállástól könnyen vezethető — <strong>engedély nem szükséges</strong>. GPS automatikus visszatéréssel, okos akadályérzékelők, akár <strong>120 km/h</strong> sebesség, és bővíthető tárhely akár <strong>256 GB</strong>-ig órányi mozi minőségű felvételhez.",
    "alt_hero": "Teljes Droniq™ Ultra HD 8K drón készlet",
    "cta": "IGEN, KÉREM A Droniq™-ot →",
    "cta_submit": "IGEN, KÉREM A Droniq™-ot",
    "form_note": "🔒 Nincs előleg · Nincs kártya · Csak átvételkor fizetsz",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Mozi minőségű videó és éles fotók",
    "feat2_h": "Okos GPS",
    "feat2_p": "Automatikus visszatérés jel vagy akkumulátor csökkenésekor",
    "feat3_h": "Akadályérzékelők",
    "feat3_p": "Észleli és elkerüli az elöl lévő akadályokat",
    "feat4_h": "Utánvét",
    "feat4_p": "Kényelmes, biztonságos, nincs előzetes fizetés",
    "countdown": "⏰ A 60% kedvezmény lejár",
    "hrs": "Óra",
    "min": "Perc",
    "sec": "Mp",
    "stock_left": "Raktárkészlet",
    "stock_right": "Csak 8 darab maradt",
    "live_tpl": "&lt;strong&gt;{n} ember&lt;/strong&gt; nézi most a Droniqot",
    "live_html": "<strong>36 ember</strong> nézi most a Droniqot",
    "order_h2": "Fejezd be a rendelést",
    "order_p": "Töltsd ki az űrlapot — csapatunk felkeres, hogy minden részletet megerősítsünk.",
    "label_name": "Teljes név *",
    "err_name": "Add meg a teljes neved (legalább 3 karakter)",
    "label_phone": "Telefonszám *",
    "err_phone": "Adj meg érvényes telefonszámot",
    "label_address": "Szállítási cím *",
    "err_address": "Adj meg teljes címet (legalább 10 karakter)",
    "why1_eye": "01 — Mozi minőségű felvételek",
    "why1_h3": "Ultra HD 8K videó — panorámák és távoli részletek egy felvételben",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">22x zoom</span><span class="tag">Széles látószög</span>',
    "why1_p": "Készíts professzionális hatású filmeket és fotókat. Látványos panorámák, éles részletek és lenyűgöző légi felvételek minden utazást évekig visszanézhető emlékekké varázsolnak. Az <strong>Ultra HD 8K</strong> kamera, a széles látószögű objektív és a <strong>22x digitális zoom</strong> lehetővé teszi, hogy a tágas tájaktól a távoli részletekig váltasz élességvesztés nélkül.",
    "why1_i": "Minden utazásból mozi minőségű emlékeket csinálj.",
    "alt_desc1": "Droniq™ Ultra HD 8K kamera 22x zoommal",
    "why2_eye": "02 — Repülj biztonságosan minden helyzetben",
    "why2_h3": "Okos GPS, akadályérzékelők és Follow Me — teljes nyugalom",
    "why2_tags": '<span class="tag">GPS visszatérés</span><span class="tag">Ütközésvédelem</span><span class="tag">Follow Me</span>',
    "why2_p": "Az AI segít észlelni az akadályokat, a GPS folyamatosan követi a pozíciót, és ha a jel gyengül vagy az akkumulátor merül, a Droniq™ <strong>automatikusan visszatér a felszállási pontra</strong>. Az automatikus felszállás, landolás és Follow Me mód minden repülést könnyebbé és biztonságosabbá tesz — még akkor is, ha még soha nem vezettél drónt.",
    "why2_i": "Magabiztosan repülsz — a Droniq™ figyel rád.",
    "aria_video": "Droniq™ GPS automatikus visszatérés és akadályelkerülés",
    "why3_eye": "03 — Az első naptól készen áll",
    "why3_h3": "Engedély nélkül · 2+ óra repülés · stabil akár 38 km/h szélben",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 akkumulátor</span><span class="tag">38 km/h szél</span>',
    "why3_p": "A Droniq™ megfelel a <strong>C0 (A1/A3)</strong> szabványnak — nincs szükség engedélyre, tanúsítványra vagy papírmunkára. A szénszálas propellerek és a fejlett stabilizálás élesen tartja a felvételeket akár <strong>38 km/h</strong> szélben is. A készlet <strong>3 nagy kapacitású akkumulátort</strong> tartalmaz, összesen több mint 2 óra repülési idővel.",
    "why3_i": "Kapcsold be, szállj fel, és kezdj el filmezni ma.",
    "alt_desc3": "Droniq™ stabil repülés akár 38 km/h szélben 3 akkumulátorral",
    "compare_label": "Miért éri meg igazán",
    "compare_h2": "Telefonkamera / alap drón vs Droniq™",
    "th_phone": "Telefon / alap drón",
    "td_price": "Ár",
    "td_price_other": "külön felszerelésre",
    "once": "egyszer",
    "td_video": "Videó",
    "td_video_other": "Átlagos telefonminőség",
    "td_video_win": "Ultra HD 8K + 22x zoom",
    "td_safety": "Biztonság",
    "td_safety_other": "Csak manuális — könnyen elveszíthető",
    "td_safety_win": "GPS visszatérés + akadályérzékelők",
    "td_flight": "Repülési idő",
    "td_flight_other": "Gyakran 20 perc alatt",
    "td_flight_win": "2+ óra 3 akkumulátorral",
    "td_license": "Engedély",
    "td_license_other": "Gyakran szükséges",
    "td_license_win": "C0 — engedély nélkül",
    "td_warranty": "Garancia",
    "td_warranty_other": "Változó",
    "td_warranty_win": "24 hónap + 30 napos visszaküldés",
    "t_eye": "⭐ 4,8/5 · Ellenőrzött vásárlás · Moderált értékelések",
    "t_h2": "Több ezer vásárló ajánlja a Droniq™-ot",
    "t1_h": "Tökéletes kezdőknek",
    "t1_p": "«Ez volt az első drónom, és féltem, hogy nehéz lesz. Perceken belül a levegőben voltam. Az automatikus felszállás és landolás megkönnyíti a vezetést, a GPS pedig nyugalmat ad az egész repülés alatt. Még azoknak is ajánlanám, akik soha nem repültek.»",
    "t1_verified": "Ellenőrzött vásárlás",
    "t2_h": "A felvétel minősége lenyűgözött",
    "t2_p": "«Elvittem egy hegyi útra, és a felvételek gyönyörűek lettek. Erősebb szélben is stabil maradt, a videók pedig élesek és simák voltak. Ennyiért fantasztikus vétel volt.»",
    "t3_h": "Teljes készlet, automatikus visszatérés",
    "t3_p": "«A szett hiánytalanul megérkezett — három akkumulátor, tartalék propellerek, minden a kezdéshez. Az automatikus visszatérés győzött meg leginkább: ha gyengül a jel vagy merül az akku, magától visszajön. Most sokkal nyugodtabban repülök.»",
    "kit_eye": "Mi van a dobozban",
    "kit_h2": "📦 Teljes, repülésre kész Droniq™ készlet",
    "alt_kit": "Teljes Droniq™ drón készlet",
    "kit1": "<strong>1× Droniq™ professzionális drón</strong> — Ultra HD 8K, GPS, akadályérzékelők",
    "kit2": "<strong>3× Nagy kapacitású akkumulátor</strong> — több mint 2 óra összes repülési idő",
    "kit3": "1× Okos távirányító",
    "kit4": "1× Gyors töltő (~30 perc)",
    "kit5": "6× Tartalék propeller",
    "kit6": "1× Kemény szállítótáska",
    "kit7": "Használati útmutató + 24 hónap garancia",
    "kit8": "Ingyenes szállítás 24/48 óra",
    "faq_eye": "Gyakori kérdések",
    "faq_h2": "Válaszok itt",
    "faq": [
        ("Hogyan rendelek?", "Töltsd ki az űrlapot névvel, telefonnal és címmel. Csapatunk felveszi veled a kapcsolatot, megválaszolja a kérdéseket, és megerősíti a szállítási részleteket."),
        ("Fizethetek átvételkor?", "Igen. Kényelem és biztonság érdekében fizethetsz átvételkor: amikor megérkezik a termék, a futárnak fizetsz. Nincs szükség kártyaadatokra."),
        ("Könnyű vezetni kezdőknek?", "Igen. A Droniq™ azoknak készült, akik még sosem vezettek drónt. A felszállás és landolás automatikus, a vezérlés intuitív, az AI pedig stabil, biztonságos repülést segít az első használattól."),
        ("Kell engedély vagy tanúsítvány?", "Nem. A Droniq™ megfelel a <strong>C0</strong> szabványnak az A1/A3 kategóriában, és engedély, tanúsítvány vagy bonyolult papírmunka nélkül használható."),
        ("Milyen a videó- és fotóminőség?", "A Droniq™ <strong>Ultra HD 8K</strong>-ban rögzít, és kivételesen éles fotókat készít. A széles látószögű objektív és a 22x digitális zoom lehetővé teszi a sima váltást a panorámák és a távoli részletek között."),
        ("Mi történik, ha a drón elveszíti a jelet vagy merül az akku?", "A beépített GPS modulnak köszönhetően a Droniq™ automatikusan visszatér a felszállási pontra, ha a jel elveszik vagy az akkumulátor alacsony."),
        ("Mi van, ha nem vagyok elégedett?", "A kézbesítéstől számított <strong>30 nap</strong> áll rendelkezésedre visszaküldésre vagy cserére, plusz 24 hónap gyártási hibákra vonatkozó garancia és ügyfélszolgálat."),
        ("Mennyibe kerül a szállítás, és mennyi ideig tart?", "A szállítás <strong>ingyenes</strong>. A rendeléseket 24 órán belül feldolgozzuk; a futár általában 24/48 munkanapon belül megérkezik."),
    ],
    "footer_blurb": "Hasznos mindennapi termékek, szállítás 24–48 óra alatt utánvéttel.",
    "footer_info": "Információ",
    "footer_about": "Rólunk",
    "footer_contact_us": "Kapcsolat",
    "footer_privacy": "Adatvédelmi szabályzat",
    "footer_terms": "Általános szerződési feltételek",
    "footer_cookie": "Cookie szabályzat",
    "footer_shipping": "Szállítási feltételek",
    "footer_refund": "Visszaküldési szabályzat",
    "footer_contact": "Kapcsolat",
    "footer_rights": "Minden jog fenntartva",
    "ty_title": "Rendelés megérkezett — Kérjük, vedd fel a visszaigazoló hívást | Droniq™",
    "ty_meta": "A Droniq™ rendelésed rögzítve. Egy utolsó lépés: vedd fel a visszaigazoló hívást az operátorunktól.",
    "ty_h1": "A rendelésed sikeresen rögzítve!",
    "ty_sub": "Szuper — a rendelésed feldolgozás alatt van. Már csak <strong>egy utolsó lépés</strong> hiányzik a befejezéshez és a szállítás indításához.",
    "ty_img_alt": "A Crazy Marketing csapat munka közben: COD call center és logisztika",
    "ty_eye": "👇 Mit kell tenned most",
    "ty_action_h": "📞 Vedd fel a visszaigazoló hívást",
    "ty_action_body": "Egyik operátorunk <strong>a következő órákban</strong> felkeres, hogy megerősítse a rendelésed.",
    "ty_warn": "Ha nem veszed fel a hívást, a rendelés automatikusan törlődik.",
    "ty_hours_h": "🕒 Elérhetőségi idő",
    "ty_hours": "<strong>Hétfő – Szombat</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Mi történik ezután",
    "ty_s1": "Vedd fel a hívást és <strong>erősítsd meg az adataidat</strong>",
    "ty_s2": "A rendelésed <strong>24–48 órán belül</strong> feladásra kerül",
    "ty_s3": "Házhozszállítás és <strong>utánvét</strong>",
    "ty_b1": "🔒 Utánvét",
    "ty_b2": "🛡️ 2 év garancia",
    "ty_b3": "🔐 SSL védelem",
    "ty_rights": "Minden jog fenntartva.",
    "index_link": "Ugrás a Droniq™ landingre",
}

COPY["hr"] = {
    "title": "Droniq™ — Ultra HD 8K dron s GPS-om i izbjegavanjem prepreka | -60%",
    "meta_desc": "Droniq™: Ultra HD 8K dron, jednostavan za letenje od prvog dana, bez licence (C0 A1/A3). GPS automatski povratak, senzori prepreka, 22x zoom, 3 baterije za 2+ sata leta. Pouzeće, besplatna dostava 24/48h.",
    "og_title": "Droniq™ — Ultra HD 8K dron | -60%",
    "og_desc": "Ultra HD 8K, GPS automatski povratak, senzori prepreka, bez licence. Pouzeće.",
    "submitting": "Slanje...",
    "cookie_text": "Koristimo bitne i treće strane kolačiće za poboljšanje iskustva i analitiku.",
    "cookie_accept": "Prihvati",
    "cookie_learn": "Saznaj više",
    "topbar": "🔥 60% POPUSTA + BESPLATNA DOSTAVA — POUZEĆE 🔥",
    "rating": "<strong>4,8/5</strong> — na temelju <strong>3.842+ verificiranih</strong> recenzija",
    "gift": "🎁 BESPLATNO: 3 baterije + tvrda torba + rezervni propeleri",
    "h1": 'Stvaraj videozapise koji oduševljavaju sve.<br>Jedan dron: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ je <strong>Ultra HD 8K dron</strong> jednostavan za letenje od prvog polijetanja — <strong>bez potrebne licence</strong>. GPS s automatskim povratkom, pametni senzori prepreka, brzine do <strong>120 km/h</strong> i proširiva pohrana do <strong>256 GB</strong> za sate snimke kino kvalitete.",
    "alt_hero": "Kompletan Droniq™ Ultra HD 8K dron kit",
    "cta": "DA, ŽELIM Droniq™ →",
    "cta_submit": "DA, ŽELIM Droniq™",
    "form_note": "🔒 Bez predujma · Bez kartice · Plaćaš samo pri dostavi",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Video kino kvalitete i oštre fotografije",
    "feat2_h": "Pametni GPS",
    "feat2_p": "Automatski povratak kad padne signal ili baterija",
    "feat3_h": "Senzori prepreka",
    "feat3_p": "Otkriva i izbjegava prepreke ispred",
    "feat4_h": "Plaćanje pouzećem",
    "feat4_p": "Praktično, sigurno, bez uplate unaprijed",
    "countdown": "⏰ Popust od 60% istječe za",
    "hrs": "Sati",
    "min": "Min",
    "sec": "Sek",
    "stock_left": "Dostupnost u skladištu",
    "stock_right": "Preostalo samo 8 komada",
    "live_tpl": "&lt;strong&gt;{n} osoba&lt;/strong&gt; trenutno gleda Droniq",
    "live_html": "<strong>36 osoba</strong> trenutno gleda Droniq",
    "order_h2": "Dovrši narudžbu",
    "order_p": "Ispuni obrazac — naš tim će te kontaktirati kako bi potvrdio svaki detalj.",
    "label_name": "Ime i prezime *",
    "err_name": "Unesi puno ime (najmanje 3 znaka)",
    "label_phone": "Broj telefona *",
    "err_phone": "Unesi važeći broj telefona",
    "label_address": "Adresa dostave *",
    "err_address": "Unesi potpunu adresu (najmanje 10 znakova)",
    "why1_eye": "01 — Snimke kino kvalitete",
    "why1_h3": "Ultra HD 8K video — panorame i udaljeni detalji u jednom kadru",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">22x zoom</span><span class="tag">Široki kut</span>',
    "why1_p": "Stvaraj filmove i fotografije profesionalnog izgleda. Spektakularne panorame, oštri detalji i impresivni zračni pogledi pretvaraju svako putovanje u uspomene koje ćeš gledati godinama. Kamera <strong>Ultra HD 8K</strong>, širokokutni objektiv i <strong>22x digitalni zoom</strong> omogućuju prijelaz od širokih krajolika do udaljenih detalja bez gubitka jasnoće.",
    "why1_i": "Pretvori svako putovanje u uspomene kino kvalitete.",
    "alt_desc1": "Droniq™ Ultra HD 8K kamera s 22x zoomom",
    "why2_eye": "02 — Leti sigurno u svakoj situaciji",
    "why2_h3": "Pametni GPS, senzori prepreka i Follow Me — potpuni mir",
    "why2_tags": '<span class="tag">GPS povratak</span><span class="tag">Antikolidija</span><span class="tag">Follow Me</span>',
    "why2_p": "AI pomaže otkriti prepreke, GPS stalno prati položaj, a ako padne signal ili baterija, Droniq™ se <strong>automatski vraća na točku polijetanja</strong>. Automatsko polijetanje, slijetanje i Follow Me način čine svaki let lakšim i sigurnijim — čak i ako nikad nisi letio dronom.",
    "why2_i": "Letiš sa samopouzdanjem — Droniq™ pazi na tebe.",
    "aria_video": "Droniq™ GPS automatski povratak i izbjegavanje prepreka",
    "why3_eye": "03 — Spreman od prvog dana",
    "why3_h3": "Bez licence · 2+ sata leta · stabilan do vjetra 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 baterije</span><span class="tag">Vjetar 38 km/h</span>',
    "why3_p": "Droniq™ zadovoljava standard <strong>C0 (A1/A3)</strong> — bez licence, certifikata ili papirologije. Propeleri od ugljičnih vlakana i napredna stabilizacija drže snimke oštrima čak i pri vjetru do <strong>38 km/h</strong>. Kit uključuje <strong>3 baterije velikog kapaciteta</strong> za više od 2 sata ukupnog leta.",
    "why3_i": "Uključi, poleti i počni snimati danas.",
    "alt_desc3": "Droniq™ stabilan let do vjetra 38 km/h s 3 baterije",
    "compare_label": "Zašto se stvarno isplati",
    "compare_h2": "Kamera telefona / osnovni dron vs Droniq™",
    "th_phone": "Telefon / osnovni dron",
    "td_price": "Cijena",
    "td_price_other": "za zasebnu opremu",
    "once": "jednokratno",
    "td_video": "Video",
    "td_video_other": "Prosječna kvaliteta telefona",
    "td_video_win": "Ultra HD 8K + 22x zoom",
    "td_safety": "Sigurnost",
    "td_safety_other": "Samo ručno — lako izgubiti",
    "td_safety_win": "GPS povratak + senzori prepreka",
    "td_flight": "Vrijeme leta",
    "td_flight_other": "Često manje od 20 minuta",
    "td_flight_win": "2+ sata s 3 baterije",
    "td_license": "Licenca",
    "td_license_other": "Često potrebna",
    "td_license_win": "C0 — bez licence",
    "td_warranty": "Jamstvo",
    "td_warranty_other": "Varira",
    "td_warranty_win": "24 mjeseca + 30 dana povrata",
    "t_eye": "⭐ 4,8/5 · Verificirana kupnja · Moderirane recenzije",
    "t_h2": "Tisuće kupaca preporučuje Droniq™",
    "t1_h": "Savršen za početnike",
    "t1_p": "«Ovo je bio moj prvi dron i brinuo sam se da će biti teško. U roku od nekoliko minuta bio sam u zraku. Automatsko polijetanje i slijetanje olakšavaju letenje, a GPS mi daje mir tijekom cijelog leta. Preporučio bih ga čak i onima koji nikad nisu letjeli.»",
    "t1_verified": "Verificirana kupnja",
    "t2_h": "Kvaliteta snimke oduševila me",
    "t2_p": "«Ponio sam ga na planinski izlet i snimke su ispale zapanjujuće. Čak i pri jačem vjetru ostao je stabilan, a videozapisi oštri i fluidni. Po ovoj cijeni bila je fantastična kupnja.»",
    "t3_h": "Kompletan kit, automatski povratak",
    "t3_p": "«Set je stigao kompletan — tri baterije, rezervni propeleri, sve za početak. Funkcija automatskog povratka najviše me uvjerila: ako padne signal ili nestane baterije, sam se vraća. Sada letim mnogo mirnije.»",
    "kit_eye": "Što je u kutiji",
    "kit_h2": "📦 Kompletan Droniq™ kit spreman za let",
    "alt_kit": "Kompletan Droniq™ dron kit",
    "kit1": "<strong>1× Profesionalni Droniq™ dron</strong> — Ultra HD 8K, GPS, senzori prepreka",
    "kit2": "<strong>3× Baterije velikog kapaciteta</strong> — više od 2 sata ukupnog leta",
    "kit3": "1× Pametni daljinski upravljač",
    "kit4": "1× Brzi punjač (~30 minuta)",
    "kit5": "6× Rezervni propeleri",
    "kit6": "1× Tvrda torba za transport",
    "kit7": "Upute za uporabu + 24-mjesečno jamstvo",
    "kit8": "Besplatna dostava 24/48 h",
    "faq_eye": "Često postavljana pitanja",
    "faq_h2": "Odgovori upravo ovdje",
    "faq": [
        ("Kako naručujem?", "Ispuni obrazac s imenom, telefonom i adresom. Naš tim će te kontaktirati, odgovoriti na pitanja i potvrditi detalje dostave."),
        ("Mogu li platiti pouzećem?", "Da. Radi praktičnosti i sigurnosti možeš platiti při dostavi: kada proizvod stigne, plaćaš kuriru. Podaci o kartici nisu potrebni."),
        ("Je li jednostavan za letenje za početnike?", "Da. Droniq™ je dizajniran za ljude koji nikad nisu letjeli dronom. Polijetanje i slijetanje su automatski, kontrole su intuitivne, a AI pomaže u stabilnom, sigurnom letu od prve uporabe."),
        ("Trebam li licencu ili certifikat?", "Ne. Droniq™ zadovoljava standard <strong>C0</strong> u kategoriji A1/A3 i može se koristiti bez licence, certifikata ili komplicirane papirologije."),
        ("Kakvu kvalitetu videa i fotografija nudi?", "Droniq™ snima u <strong>Ultra HD 8K</strong> i radi iznimno oštre fotografije. Širokokutni objektiv i 22x digitalni zoom omogućuju gladak prijelaz od panorama do udaljenih detalja."),
        ("Što ako dron izgubi signal ili padne baterija?", "Zahvaljujući ugrađenom GPS modulu, Droniq™ se automatski vraća na točku polijetanja ako se izgubi signal ili je baterija niska."),
        ("Što ako nisam zadovoljan?", "Imaš <strong>30 dana</strong> od dostave za povrat ili zamjenu, plus 24-mjesečno jamstvo na proizvodne greške i korisničku podršku."),
        ("Koliko košta dostava i koliko traje?", "Dostava je <strong>besplatna</strong>. Narudžbe obrađujemo u 24 sata; kurir obično stiže u 24/48 radnih sati."),
    ],
    "footer_blurb": "Korisni svakodnevni proizvodi, dostava u 24–48 sati s pouzećem.",
    "footer_info": "Informacije",
    "footer_about": "O nama",
    "footer_contact_us": "Kontaktirajte nas",
    "footer_privacy": "Pravila privatnosti",
    "footer_terms": "Uvjeti korištenja",
    "footer_cookie": "Pravila o kolačićima",
    "footer_shipping": "Pravila dostave",
    "footer_refund": "Pravila povrata",
    "footer_contact": "Kontakt",
    "footer_rights": "Sva prava pridržana",
    "ty_title": "Narudžba primljena — Molimo javite se na poziv za potvrdu | Droniq™",
    "ty_meta": "Tvoja Droniq™ narudžba je registrirana. Zadnji korak: javi se na poziv za potvrdu od našeg operatera.",
    "ty_h1": "Tvoja narudžba uspješno je registrirana!",
    "ty_sub": "Super — tvoja narudžba se obrađuje. Ostao je još samo <strong>jedan zadnji korak</strong> da je dovršiš i pokreneš dostavu.",
    "ty_img_alt": "Tim Crazy Marketing na poslu: COD call centar i logistika",
    "ty_eye": "👇 Što trebaš učiniti sada",
    "ty_action_h": "📞 Javi se na poziv za potvrdu",
    "ty_action_body": "Jedan od naših operatera kontaktirat će te <strong>u sljedećih nekoliko sati</strong> kako bi potvrdio narudžbu.",
    "ty_warn": "Ako se ne javiš na poziv, narudžba će se automatski otkazati.",
    "ty_hours_h": "🕒 Radno vrijeme kontakta",
    "ty_hours": "<strong>Ponedjeljak – Subota</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Što slijedi",
    "ty_s1": "Javi se na poziv i <strong>potvrdi svoje podatke</strong>",
    "ty_s2": "Tvoja narudžba bit će poslana u <strong>24–48 sati</strong>",
    "ty_s3": "Dostava na kućnu adresu i <strong>plaćanje pouzećem</strong>",
    "ty_b1": "🔒 Plaćanje pouzećem",
    "ty_b2": "🛡️ Jamstvo 2 godine",
    "ty_b3": "🔐 SSL zaštita",
    "ty_rights": "Sva prava pridržana.",
    "index_link": "Idi na Droniq™ landing",
}

# Fix typo in Croatian FAQ
COPY["hr"]["faq"][1] = (
    "Mogu li platiti pouzećem?",
    "Da. Radi praktičnosti i sigurnosti možeš platiti pri dostavi: kada proizvod stigne, plaćaš kuriru. Podaci o kartici nisu potrebni.",
)

COPY["si"] = {
    "title": "Droniq™ — Ultra HD 8K dron z GPS-om in izogibanjem oviram | -60%",
    "meta_desc": "Droniq™: Ultra HD 8K dron, enostaven za letenje od prvega dneva, brez licence (C0 A1/A3). GPS samodejni povratek, senzorji ovir, 22x zoom, 3 baterije za 2+ uri letenja. Plačilo po povzetju, brezplačna dostava 24/48h.",
    "og_title": "Droniq™ — Ultra HD 8K dron | -60%",
    "og_desc": "Ultra HD 8K, GPS samodejni povratek, senzorji ovir, brez licence. Plačilo po povzetju.",
    "submitting": "Pošiljanje...",
    "cookie_text": "Uporabljamo bistvene in tretjeosebne piškotke za boljšo izkušnjo in analitiko.",
    "cookie_accept": "Sprejmi",
    "cookie_learn": "Izvedi več",
    "topbar": "🔥 60% POPUSTA + BREZPLAČNA DOSTAVA — PLAČILO PO POVZETJU 🔥",
    "rating": "<strong>4,8/5</strong> — na podlagi <strong>3.842+ preverjenih</strong> ocen",
    "gift": "🎁 BREZPLAČNO: 3 baterije + trda torba + rezervni propelerji",
    "h1": 'Ustvari videoposnetke, ki navdušijo vse.<br>En dron: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ je <strong>Ultra HD 8K dron</strong>, enostaven za letenje že od prvega vzleta — <strong>brez potrebne licence</strong>. GPS s samodejnim povratkom, pametni senzorji ovir, hitrosti do <strong>120 km/h</strong> in razširljiva shramba do <strong>256 GB</strong> za ure posnetkov kinematografske kakovosti.",
    "alt_hero": "Popoln Droniq™ Ultra HD 8K dron komplet",
    "cta": "DA, ŽELIM Droniq™ →",
    "cta_submit": "DA, ŽELIM Droniq™",
    "form_note": "🔒 Brez pologa · Brez kartice · Plačaš šele ob dostavi",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Video kinematografske kakovosti in ostre fotografije",
    "feat2_h": "Pametni GPS",
    "feat2_p": "Samodejni povratek, ko pade signal ali baterija",
    "feat3_h": "Senzorji ovir",
    "feat3_p": "Zazna in se izogne oviram spredaj",
    "feat4_h": "Plačilo po povzetju",
    "feat4_p": "Priročno, varno, brez predplačila",
    "countdown": "⏰ 60% popust poteče čez",
    "hrs": "Ur",
    "min": "Min",
    "sec": "Sek",
    "stock_left": "Razpoložljivost v skladišču",
    "stock_right": "Ostalo le še 8 enot",
    "live_tpl": "&lt;strong&gt;{n} oseb&lt;/strong&gt; trenutno gleda Droniq",
    "live_html": "<strong>36 oseb</strong> trenutno gleda Droniq",
    "order_h2": "Dokončaj naročilo",
    "order_p": "Izpolni obrazec — naša ekipa te bo kontaktirala za potrditev vseh podrobnosti.",
    "label_name": "Polno ime *",
    "err_name": "Vnesi polno ime (vsaj 3 znake)",
    "label_phone": "Telefonska številka *",
    "err_phone": "Vnesi veljavno telefonsko številko",
    "label_address": "Naslov za dostavo *",
    "err_address": "Vnesi celoten naslov (vsaj 10 znakov)",
    "why1_eye": "01 — Posnetki kinematografske kakovosti",
    "why1_h3": "Ultra HD 8K video — panorame in oddaljene podrobnosti v enem posnetku",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">22x zoom</span><span class="tag">Široki kot</span>',
    "why1_p": "Ustvari filme in fotografije profesionalnega videza. Spektakularne panorame, ostre podrobnosti in impresivni zračni pogledi vsako potovanje spremenijo v spomine, ki jih boš gledal leta. Kamera <strong>Ultra HD 8K</strong>, širokokotni objektiv in <strong>22x digitalni zoom</strong> omogočajo prehod od širokih pokrajin do oddaljenih podrobnosti brez izgube ostrine.",
    "why1_i": "Vsako potovanje spremeni v spomine kinematografske kakovosti.",
    "alt_desc1": "Droniq™ Ultra HD 8K kamera z 22x zoomom",
    "why2_eye": "02 — Leti varno v vsaki situaciji",
    "why2_h3": "Pametni GPS, senzorji ovir in Follow Me — popoln mir",
    "why2_tags": '<span class="tag">GPS povratek</span><span class="tag">Proti trčenju</span><span class="tag">Follow Me</span>',
    "why2_p": "UI pomaga zaznati ovire, GPS nenehno sledi položaju, in če pade signal ali baterija, se Droniq™ <strong>samodejno vrne na vzletno točko</strong>. Samodejni vzlet, pristanek in način Follow Me naredijo vsak let lažji in varnejši — tudi če še nikoli nisi letel z dronom.",
    "why2_i": "Letiš samozavestno — Droniq™ te ščiti.",
    "aria_video": "Droniq™ GPS samodejni povratek in izogibanje oviram",
    "why3_eye": "03 — Pripravljen od prvega dneva",
    "why3_h3": "Brez licence · 2+ uri letenja · stabilen do vetra 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 baterije</span><span class="tag">Veter 38 km/h</span>',
    "why3_p": "Droniq™ izpolnjuje standard <strong>C0 (A1/A3)</strong> — brez licence, potrdil ali birokracije. Propelerji iz ogljikovih vlaken in napredna stabilizacija ohranjata posnetke ostre tudi pri vetru do <strong>38 km/h</strong>. Komplet vključuje <strong>3 baterije velike zmogljivosti</strong> za več kot 2 uri skupnega letenja.",
    "why3_i": "Vklopi, vzleti in začni snemati danes.",
    "alt_desc3": "Droniq™ stabilen let do vetra 38 km/h s 3 baterijami",
    "compare_label": "Zakaj se res splača",
    "compare_h2": "Kamera telefona / osnovni dron vs Droniq™",
    "th_phone": "Telefon / osnovni dron",
    "td_price": "Cena",
    "td_price_other": "za ločeno opremo",
    "once": "enkrat",
    "td_video": "Video",
    "td_video_other": "Povprečna kakovost telefona",
    "td_video_win": "Ultra HD 8K + 22x zoom",
    "td_safety": "Varnost",
    "td_safety_other": "Samo ročno — lahko izgubiš",
    "td_safety_win": "GPS povratek + senzorji ovir",
    "td_flight": "Čas letenja",
    "td_flight_other": "Pogosto manj kot 20 minut",
    "td_flight_win": "2+ uri s 3 baterijami",
    "td_license": "Licenca",
    "td_license_other": "Pogosto potrebna",
    "td_license_win": "C0 — brez licence",
    "td_warranty": "Garancija",
    "td_warranty_other": "Različno",
    "td_warranty_win": "24 mesecev + 30 dni vračila",
    "t_eye": "⭐ 4,8/5 · Preverjen nakup · Moderirane ocene",
    "t_h2": "Tisoči strank priporočajo Droniq™",
    "t1_h": "Popoln za začetnike",
    "t1_p": "«To je bil moj prvi dron in skrbelo me je, da bo težko. V nekaj minutah sem bil v zraku. Samodejni vzlet in pristanek olajšata letenje, GPS pa mi daje mir ves čas. Priporočil bi ga celo tistim, ki še nikoli niso leteli.»",
    "t1_verified": "Preverjen nakup",
    "t2_h": "Kakovost posnetkov me je prevzela",
    "t2_p": "«Vzel sem ga na gorski izlet in posnetki so bili osupljivi. Tudi ob močnejšem vetru je ostal stabilen, videoposnetki pa ostri in gladki. Za to ceno je bil fantastičen nakup.»",
    "t3_h": "Popoln komplet, samodejni povratek",
    "t3_p": "«Komplet je prispel popoln — tri baterije, rezervni propelerji, vse za začetek. Funkcija samodejnega povratka me je najbolj prepričala: če pade signal ali zmanjka baterije, se vrne sam. Zdaj letim veliko mirneje.»",
    "kit_eye": "Kaj je v škatli",
    "kit_h2": "📦 Popoln Droniq™ komplet pripravljen za let",
    "alt_kit": "Popoln Droniq™ dron komplet",
    "kit1": "<strong>1× Profesionalni Droniq™ dron</strong> — Ultra HD 8K, GPS, senzorji ovir",
    "kit2": "<strong>3× Baterije velike zmogljivosti</strong> — več kot 2 uri skupnega letenja",
    "kit3": "1× Pametni daljinski upravljalnik",
    "kit4": "1× Hitro polnilec (~30 minut)",
    "kit5": "6× Rezervni propelerji",
    "kit6": "1× Trda torba za prevoz",
    "kit7": "Navodila za uporabo + 24-mesečna garancija",
    "kit8": "Brezplačna dostava 24/48 h",
    "faq_eye": "Pogosto zastavljena vprašanja",
    "faq_h2": "Odgovori tukaj",
    "faq": [
        ("Kako naročim?", "Izpolni obrazec z imenom, telefonom in naslovom. Naša ekipa te bo kontaktirala, odgovorila na vprašanja in potrdila podrobnosti dostave."),
        ("Ali lahko plačam ob dostavi?", "Da. Zaradi udobja in varnosti lahko plačaš ob dostavi: ko izdelek prispe, plačaš kurirju. Podatki o kartici niso potrebni."),
        ("Ali je enostaven za letenje za začetnike?", "Da. Droniq™ je zasnovan za ljudi, ki še nikoli niso leteli z dronom. Vzlet in pristanek sta samodejna, upravljanje je intuitivno, UI pa pomaga pri stabilnem, varnem letu od prve uporabe."),
        ("Ali potrebujem licenco ali potrdilo?", "Ne. Droniq™ izpolnjuje standard <strong>C0</strong> v kategoriji A1/A3 in se lahko uporablja brez licence, potrdil ali zapletene birokracije."),
        ("Kakšno kakovost videa in fotografij ponuja?", "Droniq™ snema v <strong>Ultra HD 8K</strong> in dela izjemno ostre fotografije. Širokokotni objektiv in 22x digitalni zoom omogočata gladek prehod od panoram do oddaljenih podrobnosti."),
        ("Kaj če dron izgubi signal ali pade baterija?", "Zahvaljujoč vgrajenemu GPS modulu se Droniq™ samodejno vrne na vzletno točko, če se izgubi signal ali je baterija nizka."),
        ("Kaj če nisem zadovoljen?", "Imaš <strong>30 dni</strong> od dostave za vračilo ali menjavo, plus 24-mesečno garancijo na proizvodne napake in podporo strankam."),
        ("Koliko stane dostava in kako dolgo traja?", "Dostava je <strong>brezplačna</strong>. Naročila obdelamo v 24 urah; kurir običajno prispe v 24/48 delovnih urah."),
    ],
    "footer_blurb": "Uporabni vsakodnevni izdelki, dostava v 24–48 urah s plačilom po povzetju.",
    "footer_info": "Informacije",
    "footer_about": "O nas",
    "footer_contact_us": "Kontaktirajte nas",
    "footer_privacy": "Pravilnik o zasebnosti",
    "footer_terms": "Pogoji uporabe",
    "footer_cookie": "Pravilnik o piškotkih",
    "footer_shipping": "Pravilnik o dostavi",
    "footer_refund": "Pravilnik o vračilih",
    "footer_contact": "Kontakt",
    "footer_rights": "Vse pravice pridržane",
    "ty_title": "Naročilo prejeto — Prosimo, odgovorite na potrditveni klic | Droniq™",
    "ty_meta": "Tvoje naročilo Droniq™ je registrirano. Zadnji korak: odgovori na potrditveni klic našega operaterja.",
    "ty_h1": "Tvoje naročilo je bilo uspešno registrirano!",
    "ty_sub": "Odlično — tvoje naročilo se obdeluje. Ostal je še samo <strong>en zadnji korak</strong>, da ga dokončaš in začneš pošiljanje.",
    "ty_img_alt": "Ekipa Crazy Marketing pri delu: COD klicni center in logistika",
    "ty_eye": "👇 Kaj moraš narediti zdaj",
    "ty_action_h": "📞 Odgovori na potrditveni klic",
    "ty_action_body": "Eden od naših operaterjev te bo kontaktiral <strong>v naslednjih urah</strong>, da potrdi naročilo.",
    "ty_warn": "Če ne odgovoriš na klic, bo naročilo samodejno preklicano.",
    "ty_hours_h": "🕒 Kontaktne ure",
    "ty_hours": "<strong>Ponedeljek – Sobota</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Kaj sledi",
    "ty_s1": "Odgovori na klic in <strong>potrdi svoje podatke</strong>",
    "ty_s2": "Tvoje naročilo bo odposlano v <strong>24–48 urah</strong>",
    "ty_s3": "Dostava na dom in <strong>plačilo po povzetju</strong>",
    "ty_b1": "🔒 Plačilo po povzetju",
    "ty_b2": "🛡️ 2-letna garancija",
    "ty_b3": "🔐 SSL zaščita",
    "ty_rights": "Vse pravice pridržane.",
    "index_link": "Pojdi na Droniq™ landing",
}

COPY["cz"] = {
    "title": "Droniq™ — Ultra HD 8K dron s GPS a vyhýbáním překážkám | -60%",
    "meta_desc": "Droniq™: Ultra HD 8K dron, snadné létání od prvního dne, bez licence (C0 A1/A3). GPS automatický návrat, senzory překážek, 22x zoom, 3 baterie na 2+ hodiny letu. Dobírka, doprava zdarma 24/48h.",
    "og_title": "Droniq™ — Ultra HD 8K dron | -60%",
    "og_desc": "Ultra HD 8K, GPS automatický návrat, senzory překážek, bez licence. Dobírka.",
    "submitting": "Odesílání...",
    "cookie_text": "Používáme nezbytné a cookies třetích stran pro lepší zkušenost a analytiku.",
    "cookie_accept": "Přijmout",
    "cookie_learn": "Zjistit více",
    "topbar": "🔥 SLEVA 60 % + DOPRAVA ZDARMA — DOBÍRKA 🔥",
    "rating": "<strong>4,8/5</strong> — na základě <strong>3 842+ ověřených</strong> recenzí",
    "gift": "🎁 ZDARMA: 3 baterie + pevné pouzdro + náhradní vrtule",
    "h1": 'Natočte videa, která ohromí všechny.<br>Jeden dron: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ je <strong>Ultra HD 8K dron</strong>, se kterým se snadno létá už od prvního vzletu — <strong>bez nutnosti licence</strong>. GPS s automatickým návratem, chytré senzory překážek, rychlosti až <strong>120 km/h</strong> a rozšířitelné úložiště až <strong>256 GB</strong> pro hodiny záznamu ve filmové kvalitě.",
    "alt_hero": "Kompletní sada Droniq™ Ultra HD 8K dron",
    "cta": "ANO, CHCI Droniq™ →",
    "cta_submit": "ANO, CHCI Droniq™",
    "form_note": "🔒 Bez zálohy · Bez karty · Platíte až při doručení",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Video ve filmové kvalitě a ostré fotky",
    "feat2_h": "Chytré GPS",
    "feat2_p": "Automatický návrat při poklesu signálu nebo baterie",
    "feat3_h": "Senzory překážek",
    "feat3_p": "Detekuje a vyhýbá se překážkám vpředu",
    "feat4_h": "Dobírka",
    "feat4_p": "Pohodlné, bezpečné, bez platby předem",
    "countdown": "⏰ Sleva 60 % vyprší za",
    "hrs": "Hod",
    "min": "Min",
    "sec": "Sek",
    "stock_left": "Dostupnost ve skladu",
    "stock_right": "Zbývá jen 8 kusů",
    "live_tpl": "&lt;strong&gt;{n} lidí&lt;/strong&gt; právě prohlíží Droniq",
    "live_html": "<strong>36 lidí</strong> právě prohlíží Droniq",
    "order_h2": "Dokončete objednávku",
    "order_p": "Vyplňte formulář — náš tým vás kontaktuje a potvrdí všechny detaily.",
    "label_name": "Celé jméno *",
    "err_name": "Zadejte celé jméno (alespoň 3 znaky)",
    "label_phone": "Telefonní číslo *",
    "err_phone": "Zadejte platné telefonní číslo",
    "label_address": "Doručovací adresa *",
    "err_address": "Zadejte kompletní adresu (alespoň 10 znaků)",
    "why1_eye": "01 — Záznam ve filmové kvalitě",
    "why1_h3": "Ultra HD 8K video — panoramata i vzdálené detaily v jednom záběru",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">22x zoom</span><span class="tag">Široký úhel</span>',
    "why1_p": "Natočte filmy a fotografie s profesionálním vzhledem. Velkolepá panoramata, ostré detaily a působivé letecké pohledy promění každou cestu ve vzpomínky, ke kterým se budete vracet roky. Fotoaparát <strong>Ultra HD 8K</strong>, širokoúhlý objektiv a <strong>22x digitální zoom</strong> umožňují přechod od širokých krajin ke vzdáleným detailům bez ztráty ostrosti.",
    "why1_i": "Proměňte každou cestu ve vzpomínky ve filmové kvalitě.",
    "alt_desc1": "Droniq™ Ultra HD 8K kamera s 22x zoomem",
    "why2_eye": "02 — Létejte bezpečně v každé situaci",
    "why2_h3": "Chytré GPS, senzory překážek a Follow Me — naprostý klid",
    "why2_tags": '<span class="tag">GPS návrat</span><span class="tag">Antikolize</span><span class="tag">Follow Me</span>',
    "why2_p": "AI pomáhá detekovat překážky, GPS neustále sleduje polohu a pokud klesne signál nebo baterie, Droniq™ se <strong>automaticky vrátí na místo vzletu</strong>. Automatický vzlet, přistání a režim Follow Me usnadňují a zabezpečují každý let — i když jste nikdy dronem nelétali.",
    "why2_i": "Létáte s jistotou — Droniq™ vás chrání.",
    "aria_video": "Droniq™ GPS automatický návrat a vyhýbání překážkám",
    "why3_eye": "03 — Připraven od prvního dne",
    "why3_h3": "Bez licence · 2+ hodiny letu · stabilní do větru 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 baterie</span><span class="tag">Vítr 38 km/h</span>',
    "why3_p": "Droniq™ splňuje standard <strong>C0 (A1/A3)</strong> — bez licence, certifikátů nebo papírování. Uhlíkové vrtule a pokročilá stabilizace udržují záběry ostré i při větru do <strong>38 km/h</strong>. Sada obsahuje <strong>3 baterie s vysokou kapacitou</strong> na více než 2 hodiny celkového letu.",
    "why3_i": "Zapněte, vzlétněte a začněte natáčet ještě dnes.",
    "alt_desc3": "Droniq™ stabilní let do větru 38 km/h se 3 bateriemi",
    "compare_label": "Proč se to opravdu vyplatí",
    "compare_h2": "Fotoaparát telefonu / základní dron vs Droniq™",
    "th_phone": "Telefon / základní dron",
    "td_price": "Cena",
    "td_price_other": "za samostatné vybavení",
    "once": "jednorázově",
    "td_video": "Video",
    "td_video_other": "Průměrná kvalita telefonu",
    "td_video_win": "Ultra HD 8K + 22x zoom",
    "td_safety": "Bezpečnost",
    "td_safety_other": "Jen manuálně — snadno ztratíte",
    "td_safety_win": "GPS návrat + senzory překážek",
    "td_flight": "Doba letu",
    "td_flight_other": "Často méně než 20 minut",
    "td_flight_win": "2+ hodiny se 3 bateriemi",
    "td_license": "Licence",
    "td_license_other": "Často nutná",
    "td_license_win": "C0 — bez licence",
    "td_warranty": "Záruka",
    "td_warranty_other": "Různá",
    "td_warranty_win": "24 měsíců + 30 dní na vrácení",
    "t_eye": "⭐ 4,8/5 · Ověřený nákup · Moderované recenze",
    "t_h2": "Tisíce zákazníků doporučují Droniq™",
    "t1_h": "Ideální pro začátečníky",
    "t1_p": "«Byl to můj první dron a bál jsem se, že to bude těžké. Během minut jsem byl ve vzduchu. Automatický vzlet a přistání usnadňují létání a GPS mi dává klid po celý let. Doporučil bych ho i lidem, kteří nikdy nelétali.»",
    "t1_verified": "Ověřený nákup",
    "t2_h": "Kvalita záznamu mě ohromila",
    "t2_p": "«Vzal jsem ho na horský výlet a záběry vyšly úžasně. I v silnějším větru zůstal stabilní a videa byla ostrá a plynulá. Za tuto cenu to byl fantastický nákup.»",
    "t3_h": "Kompletní sada, automatický návrat",
    "t3_p": "«Sada dorazila kompletní — tři baterie, náhradní vrtule, vše pro start. Nejvíce mě přesvědčila funkce automatického návratu: když klesne signál nebo dojde baterie, vrátí se sám. Teď létám mnohem klidněji.»",
    "kit_eye": "Co je v krabici",
    "kit_h2": "📦 Kompletní sada Droniq™ připravená k letu",
    "alt_kit": "Kompletní sada dronu Droniq™",
    "kit1": "<strong>1× Profesionální dron Droniq™</strong> — Ultra HD 8K, GPS, senzory překážek",
    "kit2": "<strong>3× Baterie s vysokou kapacitou</strong> — více než 2 hodiny celkového letu",
    "kit3": "1× Chytrý dálkový ovladač",
    "kit4": "1× Rychlá nabíječka (~30 minut)",
    "kit5": "6× Náhradní vrtule",
    "kit6": "1× Pevné přepravní pouzdro",
    "kit7": "Uživatelský manuál + 24měsíční záruka",
    "kit8": "Doprava zdarma 24/48 h",
    "faq_eye": "Často kladené otázky",
    "faq_h2": "Odpovědi přímo zde",
    "faq": [
        ("Jak objednám?", "Vyplňte formulář jménem, telefonem a adresou. Náš tým vás kontaktuje, zodpoví otázky a potvrdí detaily doručení."),
        ("Mohu platit na dobírku?", "Ano. Pro pohodlí a bezpečnost můžete platit při doručení: když produkt dorazí, zaplatíte kurýrovi. Údaje o kartě nejsou potřeba."),
        ("Je snadné létat pro začátečníky?", "Ano. Droniq™ je navržen pro lidi, kteří nikdy nelétali dronem. Vzlet a přistání jsou automatické, ovládání intuitivní a AI pomáhá udržet stabilní a bezpečný let od prvního použití."),
        ("Potřebuji licenci nebo certifikát?", "Ne. Droniq™ splňuje standard <strong>C0</strong> v kategorii A1/A3 a lze jej používat bez licence, certifikátů nebo složitého papírování."),
        ("Jakou kvalitu videa a fotek nabízí?", "Droniq™ natáčí v <strong>Ultra HD 8K</strong> a pořizuje výjimečně ostré fotky. Širokoúhlý objektiv a 22x digitální zoom umožňují plynulý přechod od panoramat ke vzdáleným detailům."),
        ("Co když dron ztratí signál nebo klesne baterie?", "Díky vestavěnému GPS modulu se Droniq™ automaticky vrátí na místo vzletu, pokud se ztratí signál nebo je baterie nízká."),
        ("Co když nejsem spokojen?", "Máte <strong>30 dní</strong> od doručení na vrácení nebo výměnu, plus 24měsíční záruku na výrobní vady a zákaznickou podporu."),
        ("Kolik stojí doprava a jak dlouho trvá?", "Doprava je <strong>zdarma</strong>. Objednávky zpracujeme do 24 hodin; kurýr obvykle dorazí do 24/48 pracovních hodin."),
    ],
    "footer_blurb": "Užitečné produkty pro každodenní život, doručení do 24–48 hodin na dobírku.",
    "footer_info": "Informace",
    "footer_about": "O nás",
    "footer_contact_us": "Kontaktujte nás",
    "footer_privacy": "Zásady ochrany osobních údajů",
    "footer_terms": "Obchodní podmínky",
    "footer_cookie": "Zásady cookies",
    "footer_shipping": "Doprava",
    "footer_refund": "Vrácení zboží",
    "footer_contact": "Kontakt",
    "footer_rights": "Všechna práva vyhrazena",
    "ty_title": "Objednávka přijata — Prosím zvedněte potvrzovací hovor | Droniq™",
    "ty_meta": "Vaše objednávka Droniq™ byla zaregistrována. Poslední krok: zvedněte potvrzovací hovor od našeho operátora.",
    "ty_h1": "Vaše objednávka byla úspěšně zaregistrována!",
    "ty_sub": "Skvělé — vaše objednávka se zpracovává. Zbývá jen <strong>jeden poslední krok</strong> k dokončení a zahájení odeslání.",
    "ty_img_alt": "Tým Crazy Marketing při práci: COD call centrum a logistika",
    "ty_eye": "👇 Co musíte udělat teď",
    "ty_action_h": "📞 Zvedněte potvrzovací hovor",
    "ty_action_body": "Jeden z našich operátorů vás kontaktuje <strong>během následujících hodin</strong>, aby potvrdil objednávku.",
    "ty_warn": "Pokud hovor nezvednete, objednávka bude automaticky zrušena.",
    "ty_hours_h": "🕒 Kontaktní hodiny",
    "ty_hours": "<strong>Pondělí – Sobota</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Co bude dál",
    "ty_s1": "Zvedněte hovor a <strong>potvrďte své údaje</strong>",
    "ty_s2": "Vaše objednávka bude odeslána do <strong>24–48 hodin</strong>",
    "ty_s3": "Doručení domů a <strong>dobírka</strong>",
    "ty_b1": "🔒 Dobírka",
    "ty_b2": "🛡️ 2letá záruka",
    "ty_b3": "🔐 SSL ochrana",
    "ty_rights": "Všechna práva vyhrazena.",
    "index_link": "Přejít na landing Droniq™",
}

COPY["sk"] = {
    "title": "Droniq™ — Ultra HD 8K dron s GPS a vyhýbaním prekážkam | -60%",
    "meta_desc": "Droniq™: Ultra HD 8K dron, ľahké lietanie od prvého dňa, bez licencie (C0 A1/A3). GPS automatický návrat, senzory prekážok, 22x zoom, 3 batérie na 2+ hodiny letu. Dobierka, doprava zdarma 24/48h.",
    "og_title": "Droniq™ — Ultra HD 8K dron | -60%",
    "og_desc": "Ultra HD 8K, GPS automatický návrat, senzory prekážok, bez licencie. Dobierka.",
    "submitting": "Odosielanie...",
    "cookie_text": "Používame nevyhnutné a cookies tretích strán na zlepšenie skúsenosti a analytiku.",
    "cookie_accept": "Prijať",
    "cookie_learn": "Zistiť viac",
    "topbar": "🔥 ZĽAVA 60 % + DOPRAVA ZADARMO — DOBIERKA 🔥",
    "rating": "<strong>4,8/5</strong> — na základe <strong>3 842+ overených</strong> recenzií",
    "gift": "🎁 ZADARMO: 3 batérie + pevné puzdro + náhradné vrtule",
    "h1": 'Natočte videá, ktoré ohúria všetkých.<br>Jeden dron: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ je <strong>Ultra HD 8K dron</strong>, s ktorým sa ľahko lietá už od prvého vzletu — <strong>bez potreby licencie</strong>. GPS s automatickým návratom, inteligentné senzory prekážok, rýchlosti až <strong>120 km/h</strong> a rozšíriteľné úložisko až <strong>256 GB</strong> na hodiny záznamu vo filmovej kvalite.",
    "alt_hero": "Kompletná sada Droniq™ Ultra HD 8K dron",
    "cta": "ÁNO, CHCEM Droniq™ →",
    "cta_submit": "ÁNO, CHCEM Droniq™",
    "form_note": "🔒 Bez zálohy · Bez karty · Platíte až pri doručení",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Video vo filmovej kvalite a ostré fotky",
    "feat2_h": "Inteligentné GPS",
    "feat2_p": "Automatický návrat pri poklese signálu alebo batérie",
    "feat3_h": "Senzory prekážok",
    "feat3_p": "Deteguje a vyhýba sa prekážkam vpredu",
    "feat4_h": "Dobierka",
    "feat4_p": "Pohodlné, bezpečné, bez platby vopred",
    "countdown": "⏰ Zľava 60 % vyprší o",
    "hrs": "Hod",
    "min": "Min",
    "sec": "Sek",
    "stock_left": "Dostupnosť v sklade",
    "stock_right": "Zostáva len 8 kusov",
    "live_tpl": "&lt;strong&gt;{n} ľudí&lt;/strong&gt; práve prezerá Droniq",
    "live_html": "<strong>36 ľudí</strong> práve prezerá Droniq",
    "order_h2": "Dokončite objednávku",
    "order_p": "Vyplňte formulár — náš tím vás kontaktuje a potvrdí všetky detaily.",
    "label_name": "Celé meno *",
    "err_name": "Zadajte celé meno (aspoň 3 znaky)",
    "label_phone": "Telefónne číslo *",
    "err_phone": "Zadajte platné telefónne číslo",
    "label_address": "Doručovacia adresa *",
    "err_address": "Zadajte kompletnú adresu (aspoň 10 znakov)",
    "why1_eye": "01 — Záznam vo filmovej kvalite",
    "why1_h3": "Ultra HD 8K video — panorámy aj vzdialené detaily v jednom zábere",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">22x zoom</span><span class="tag">Široký uhol</span>',
    "why1_p": "Natočte filmy a fotografie s profesionálnym vzhľadom. Veľkolepé panorámy, ostré detaily a pôsobivé letecké pohľady premenia každú cestu na spomienky, ku ktorým sa budete vracať roky. Fotoaparát <strong>Ultra HD 8K</strong>, širokouhlý objektív a <strong>22x digitálny zoom</strong> umožňujú prechod od širokých krajín k vzdialeným detailom bez straty ostrosti.",
    "why1_i": "Premeňte každú cestu na spomienky vo filmovej kvalite.",
    "alt_desc1": "Droniq™ Ultra HD 8K kamera s 22x zoomom",
    "why2_eye": "02 — Lietajte bezpečne v každej situácii",
    "why2_h3": "Inteligentné GPS, senzory prekážok a Follow Me — úplný pokoj",
    "why2_tags": '<span class="tag">GPS návrat</span><span class="tag">Antikolízia</span><span class="tag">Follow Me</span>',
    "why2_p": "AI pomáha detegovať prekážky, GPS neustále sleduje polohu a ak klesne signál alebo batéria, Droniq™ sa <strong>automaticky vráti na miesto vzletu</strong>. Automatický vzlet, pristátie a režim Follow Me uľahčujú a zabezpečujú každý let — aj keď ste nikdy dronom nelietali.",
    "why2_i": "Lietate s istotou — Droniq™ vás chráni.",
    "aria_video": "Droniq™ GPS automatický návrat a vyhýbanie prekážkam",
    "why3_eye": "03 — Pripravený od prvého dňa",
    "why3_h3": "Bez licencie · 2+ hodiny letu · stabilný do vetra 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 batérie</span><span class="tag">Vietor 38 km/h</span>',
    "why3_p": "Droniq™ spĺňa štandard <strong>C0 (A1/A3)</strong> — bez licencie, certifikátov alebo papierovania. Uhlíkové vrtule a pokročilá stabilizácia udržujú zábery ostré aj pri vetre do <strong>38 km/h</strong>. Sada obsahuje <strong>3 batérie s vysokou kapacitou</strong> na viac ako 2 hodiny celkového letu.",
    "why3_i": "Zapnite, vzleťte a začnite natáčať ešte dnes.",
    "alt_desc3": "Droniq™ stabilný let do vetra 38 km/h s 3 batériami",
    "compare_label": "Prečo sa to naozaj oplatí",
    "compare_h2": "Fotoaparát telefónu / základný dron vs Droniq™",
    "th_phone": "Telefón / základný dron",
    "td_price": "Cena",
    "td_price_other": "za samostatné vybavenie",
    "once": "raz",
    "td_video": "Video",
    "td_video_other": "Priemerná kvalita telefónu",
    "td_video_win": "Ultra HD 8K + 22x zoom",
    "td_safety": "Bezpečnosť",
    "td_safety_other": "Len manuálne — ľahko stratíte",
    "td_safety_win": "GPS návrat + senzory prekážok",
    "td_flight": "Doba letu",
    "td_flight_other": "Často menej ako 20 minút",
    "td_flight_win": "2+ hodiny s 3 batériami",
    "td_license": "Licencia",
    "td_license_other": "Často potrebná",
    "td_license_win": "C0 — bez licencie",
    "td_warranty": "Záruka",
    "td_warranty_other": "Rôzna",
    "td_warranty_win": "24 mesiacov + 30 dní na vrátenie",
    "t_eye": "⭐ 4,8/5 · Overený nákup · Moderované recenzie",
    "t_h2": "Tisíce zákazníkov odporúčajú Droniq™",
    "t1_h": "Ideálny pre začiatočníkov",
    "t1_p": "«Bol to môj prvý dron a bál som sa, že to bude ťažké. Za pár minút som bol vo vzduchu. Automatický vzlet a pristátie uľahčujú lietanie a GPS mi dáva pokoj počas celého letu. Odporučil by som ho aj ľuďom, ktorí nikdy nelietali.»",
    "t1_verified": "Overený nákup",
    "t2_h": "Kvalita záznamu ma ohúrila",
    "t2_p": "«Vzal som ho na horský výlet a zábery vyšli úžasne. Aj v silnejšom vetre zostal stabilný a videá boli ostré a plynulé. Za túto cenu to bol fantastický nákup.»",
    "t3_h": "Kompletná sada, automatický návrat",
    "t3_p": "«Sada dorazila kompletná — tri batérie, náhradné vrtule, všetko na štart. Najviac ma presvedčila funkcia automatického návratu: keď klesne signál alebo dôjde batéria, vráti sa sám. Teraz lietam oveľa pokojnejšie.»",
    "kit_eye": "Čo je v krabici",
    "kit_h2": "📦 Kompletná sada Droniq™ pripravená na let",
    "alt_kit": "Kompletná sada dronu Droniq™",
    "kit1": "<strong>1× Profesionálny dron Droniq™</strong> — Ultra HD 8K, GPS, senzory prekážok",
    "kit2": "<strong>3× Batérie s vysokou kapacitou</strong> — viac ako 2 hodiny celkového letu",
    "kit3": "1× Inteligentný diaľkový ovládač",
    "kit4": "1× Rýchla nabíjačka (~30 minút)",
    "kit5": "6× Náhradné vrtule",
    "kit6": "1× Pevné prepravné puzdro",
    "kit7": "Používateľský manuál + 24-mesačná záruka",
    "kit8": "Doprava zadarmo 24/48 h",
    "faq_eye": "Často kladené otázky",
    "faq_h2": "Odpovede priamo tu",
    "faq": [
        ("Ako objednám?", "Vyplňte formulár menom, telefónom a adresou. Náš tím vás kontaktuje, zodpovie otázky a potvrdí detaily doručenia."),
        ("Môžem platiť na dobierku?", "Áno. Pre pohodlie a bezpečnosť môžete platiť pri doručení: keď produkt dorazí, zaplatíte kuriérovi. Údaje o karte nie sú potrebné."),
        ("Je ľahké lietať pre začiatočníkov?", "Áno. Droniq™ je navrhnutý pre ľudí, ktorí nikdy nelietali dronom. Vzlet a pristátie sú automatické, ovládanie intuitívne a AI pomáha udržať stabilný a bezpečný let od prvého použitia."),
        ("Potrebujem licenciu alebo certifikát?", "Nie. Droniq™ spĺňa štandard <strong>C0</strong> v kategórii A1/A3 a možno ho používať bez licencie, certifikátov alebo zložitého papierovania."),
        ("Akú kvalitu videa a fotiek ponúka?", "Droniq™ natáča v <strong>Ultra HD 8K</strong> a robí výnimočne ostré fotky. Širokouhlý objektív a 22x digitálny zoom umožňujú plynulý prechod od panorám k vzdialeným detailom."),
        ("Čo ak dron stratí signál alebo klesne batéria?", "Vďaka vstavanému GPS modulu sa Droniq™ automaticky vráti na miesto vzletu, ak sa stratí signál alebo je batéria nízka."),
        ("Čo ak nie som spokojný?", "Máte <strong>30 dní</strong> od doručenia na vrátenie alebo výmenu, plus 24-mesačnú záruku na výrobné chyby a zákaznícku podporu."),
        ("Koľko stojí doprava a ako dlho trvá?", "Doprava je <strong>zadarmo</strong>. Objednávky spracujeme do 24 hodín; kuriér zvyčajne dorazí do 24/48 pracovných hodín."),
    ],
    "footer_blurb": "Užitočné produkty na každý deň, doručenie do 24–48 hodín na dobierku.",
    "footer_info": "Informácie",
    "footer_about": "O nás",
    "footer_contact_us": "Kontaktujte nás",
    "footer_privacy": "Zásady ochrany osobných údajov",
    "footer_terms": "Obchodné podmienky",
    "footer_cookie": "Zásady cookies",
    "footer_shipping": "Doprava",
    "footer_refund": "Vrátenie tovaru",
    "footer_contact": "Kontakt",
    "footer_rights": "Všetky práva vyhradené",
    "ty_title": "Objednávka prijatá — Prosím zdvihnite potvrdzovací hovor | Droniq™",
    "ty_meta": "Vaša objednávka Droniq™ bola zaregistrovaná. Posledný krok: zdvihnite potvrdzovací hovor od nášho operátora.",
    "ty_h1": "Vaša objednávka bola úspešne zaregistrovaná!",
    "ty_sub": "Skvelé — vaša objednávka sa spracováva. Zostáva len <strong>jeden posledný krok</strong> na dokončenie a spustenie odoslania.",
    "ty_img_alt": "Tím Crazy Marketing pri práci: COD call centrum a logistika",
    "ty_eye": "👇 Čo musíte urobiť teraz",
    "ty_action_h": "📞 Zdvihnite potvrdzovací hovor",
    "ty_action_body": "Jeden z našich operátorov vás kontaktuje <strong>v nasledujúcich hodinách</strong>, aby potvrdil objednávku.",
    "ty_warn": "Ak hovor nezodvihnete, objednávka bude automaticky zrušená.",
    "ty_hours_h": "🕒 Kontaktné hodiny",
    "ty_hours": "<strong>Pondelok – Sobota</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Čo bude ďalej",
    "ty_s1": "Zdvihnite hovor a <strong>potvrďte svoje údaje</strong>",
    "ty_s2": "Vaša objednávka bude odoslaná do <strong>24–48 hodín</strong>",
    "ty_s3": "Doručenie domov a <strong>dobierka</strong>",
    "ty_b1": "🔒 Dobierka",
    "ty_b2": "🛡️ 2-ročná záruka",
    "ty_b3": "🔐 SSL ochrana",
    "ty_rights": "Všetky práva vyhradené.",
    "index_link": "Prejsť na landing Droniq™",
}

COPY["pl"] = {
    "title": "Droniq™ — Dron Ultra HD 8K z GPS i omijaniem przeszkód | -60%",
    "meta_desc": "Droniq™: dron Ultra HD 8K, łatwy w lataniu od pierwszego dnia, bez licencji (C0 A1/A3). Automatyczny powrót GPS, czujniki przeszkód, zoom 22x, 3 baterie na 2+ godziny lotu. Płatność przy odbiorze, darmowa dostawa 24/48h.",
    "og_title": "Droniq™ — Dron Ultra HD 8K | -60%",
    "og_desc": "Ultra HD 8K, automatyczny powrót GPS, czujniki przeszkód, bez licencji. Płatność przy odbiorze.",
    "submitting": "Wysyłanie...",
    "cookie_text": "Używamy niezbędnych i zewnętrznych plików cookie, aby poprawić Twoje doświadczenie i do analityki.",
    "cookie_accept": "Akceptuj",
    "cookie_learn": "Dowiedz się więcej",
    "topbar": "🔥 60% ZNIŻKI + DARMOWA DOSTAWA — PŁATNOŚĆ PRZY ODBIORZE 🔥",
    "rating": "<strong>4,8/5</strong> — na podstawie <strong>3 842+ zweryfikowanych</strong> opinii",
    "gift": "🎁 GRATIS: 3 baterie + twarda walizka + zapasowe śmigła",
    "h1": 'Twórz filmy, które zachwycą wszystkich.<br>Jeden dron: <span class="hl">Droniq™</span>',
    "lead": "Droniq™ to <strong>dron Ultra HD 8K</strong>, którym łatwo latać od pierwszego startu — <strong>bez wymaganej licencji</strong>. GPS z automatycznym powrotem, inteligentne czujniki przeszkód, prędkości do <strong>120 km/h</strong> i rozszerzalna pamięć do <strong>256 GB</strong> na godziny materiału w jakości kinowej.",
    "alt_hero": "Kompletny zestaw Droniq™ dron Ultra HD 8K",
    "cta": "TAK, CHCĘ Droniq™ →",
    "cta_submit": "TAK, CHCĘ Droniq™",
    "form_note": "🔒 Bez zaliczki · Bez karty · Płacisz tylko przy odbiorze",
    "feat1_h": "Ultra HD 8K",
    "feat1_p": "Wideo w jakości kinowej i ostre zdjęcia",
    "feat2_h": "Inteligentny GPS",
    "feat2_p": "Automatyczny powrót przy spadku sygnału lub baterii",
    "feat3_h": "Czujniki przeszkód",
    "feat3_p": "Wykrywa i omija przeszkody z przodu",
    "feat4_h": "Płatność przy odbiorze",
    "feat4_p": "Wygodnie, bezpiecznie, bez płatności z góry",
    "countdown": "⏰ Zniżka 60% wygasa za",
    "hrs": "Godz",
    "min": "Min",
    "sec": "Sek",
    "stock_left": "Dostępność w magazynie",
    "stock_right": "Zostało tylko 8 sztuk",
    "live_tpl": "&lt;strong&gt;{n} osób&lt;/strong&gt; ogląda teraz Droniq",
    "live_html": "<strong>36 osób</strong> ogląda teraz Droniq",
    "order_h2": "Dokończ zamówienie",
    "order_p": "Wypełnij formularz — nasz zespół skontaktuje się, aby potwierdzić każdy szczegół.",
    "label_name": "Imię i nazwisko *",
    "err_name": "Wpisz pełne imię i nazwisko (co najmniej 3 znaki)",
    "label_phone": "Numer telefonu *",
    "err_phone": "Wpisz prawidłowy numer telefonu",
    "label_address": "Adres dostawy *",
    "err_address": "Wpisz pełny adres (co najmniej 10 znaków)",
    "why1_eye": "01 — Materiał w jakości kinowej",
    "why1_h3": "Wideo Ultra HD 8K — panoramy i odległe detale w jednym ujęciu",
    "why1_tags": '<span class="tag">Ultra HD 8K</span><span class="tag">Zoom 22x</span><span class="tag">Szeroki kąt</span>',
    "why1_p": "Twórz filmy i zdjęcia o profesjonalnym wyglądzie. Spektakularne panoramy, ostre detale i imponujące widoki z powietrza zamieniają każdą podróż we wspomnienia, do których będziesz wracać latami. Aparat <strong>Ultra HD 8K</strong>, obiektyw szerokokątny i <strong>cyfrowy zoom 22x</strong> pozwalają przejść od szerokich krajobrazów do odległych detali bez utraty ostrości.",
    "why1_i": "Zamień każdą podróż we wspomnienia w jakości kinowej.",
    "alt_desc1": "Aparat Droniq™ Ultra HD 8K z zoomem 22x",
    "why2_eye": "02 — Lataj bezpiecznie w każdej sytuacji",
    "why2_h3": "Inteligentny GPS, czujniki przeszkód i Follow Me — pełny spokój",
    "why2_tags": '<span class="tag">Powrót GPS</span><span class="tag">Antykolizja</span><span class="tag">Follow Me</span>',
    "why2_p": "AI pomaga wykrywać przeszkody, GPS stale śledzi pozycję, a jeśli spadnie sygnał lub bateria, Droniq™ <strong>automatycznie wraca do punktu startu</strong>. Automatyczny start, lądowanie i tryb Follow Me czynią każdy lot łatwiejszym i bezpieczniejszym — nawet jeśli nigdy nie latałeś dronem.",
    "why2_i": "Lataj z pewnością — Droniq™ Cię chroni.",
    "aria_video": "Automatyczny powrót GPS i omijanie przeszkód Droniq™",
    "why3_eye": "03 — Gotowy od pierwszego dnia",
    "why3_h3": "Bez licencji · 2+ godziny lotu · stabilny przy wietrze do 38 km/h",
    "why3_tags": '<span class="tag">C0 (A1/A3)</span><span class="tag">3 baterie</span><span class="tag">Wiatr 38 km/h</span>',
    "why3_p": "Droniq™ spełnia standard <strong>C0 (A1/A3)</strong> — bez licencji, certyfikatów i papierkowej roboty. Śmigła z włókna węglowego i zaawansowana stabilizacja utrzymują ujęcia ostre nawet przy wietrze do <strong>38 km/h</strong>. Zestaw zawiera <strong>3 baterie o dużej pojemności</strong> na ponad 2 godziny łącznego czasu lotu.",
    "why3_i": "Włącz, wystartuj i zacznij filmować już dziś.",
    "alt_desc3": "Stabilny lot Droniq™ przy wietrze do 38 km/h z 3 bateriami",
    "compare_label": "Dlaczego naprawdę się opłaca",
    "compare_h2": "Aparat w telefonie / podstawowy dron vs Droniq™",
    "th_phone": "Telefon / podstawowy dron",
    "td_price": "Cena",
    "td_price_other": "za osobny sprzęt",
    "once": "raz",
    "td_video": "Wideo",
    "td_video_other": "Przeciętna jakość telefonu",
    "td_video_win": "Ultra HD 8K + zoom 22x",
    "td_safety": "Bezpieczeństwo",
    "td_safety_other": "Tylko ręcznie — łatwo zgubić",
    "td_safety_win": "Powrót GPS + czujniki przeszkód",
    "td_flight": "Czas lotu",
    "td_flight_other": "Często poniżej 20 minut",
    "td_flight_win": "2+ godziny z 3 bateriami",
    "td_license": "Licencja",
    "td_license_other": "Często wymagana",
    "td_license_win": "C0 — bez licencji",
    "td_warranty": "Gwarancja",
    "td_warranty_other": "Różna",
    "td_warranty_win": "24 miesiące + 30 dni na zwrot",
    "t_eye": "⭐ 4,8/5 · Zweryfikowany zakup · Moderowane opinie",
    "t_h2": "Tysiące klientów poleca Droniq™",
    "t1_h": "Idealny dla początkujących",
    "t1_p": "«To był mój pierwszy dron i bałem się, że będzie trudno. W ciągu kilku minut byłem w powietrzu. Automatyczny start i lądowanie ułatwiają latanie, a GPS daje spokój przez cały lot. Poleciłbym go nawet osobom, które nigdy nie latały.»",
    "t1_verified": "Zweryfikowany zakup",
    "t2_h": "Jakość materiału mnie zachwyciła",
    "t2_p": "«Zabrałem go w górską wyprawę i ujęcia wyszły oszałamiająco. Nawet przy silniejszym wietrze był stabilny, a filmy ostre i płynne. W tej cenie to był fantastyczny zakup.»",
    "t3_h": "Kompletny zestaw, automatyczny powrót",
    "t3_p": "«Zestaw dotarł kompletny — trzy baterie, zapasowe śmigła, wszystko do startu. Najbardziej przekonała mnie funkcja automatycznego powrotu: jeśli spadnie sygnał lub skończy się bateria, wraca sam. Teraz latam dużo spokojniej.»",
    "kit_eye": "Co jest w pudełku",
    "kit_h2": "📦 Kompletny zestaw Droniq™ gotowy do lotu",
    "alt_kit": "Kompletny zestaw drona Droniq™",
    "kit1": "<strong>1× Profesjonalny dron Droniq™</strong> — Ultra HD 8K, GPS, czujniki przeszkód",
    "kit2": "<strong>3× Baterie o dużej pojemności</strong> — ponad 2 godziny łącznego czasu lotu",
    "kit3": "1× Inteligentny pilot zdalnego sterowania",
    "kit4": "1× Szybka ładowarka (~30 minut)",
    "kit5": "6× Zapasowe śmigła",
    "kit6": "1× Twarda walizka transportowa",
    "kit7": "Instrukcja obsługi + 24-miesięczna gwarancja",
    "kit8": "Darmowa dostawa 24/48 h",
    "faq_eye": "Często zadawane pytania",
    "faq_h2": "Odpowiedzi tutaj",
    "faq": [
        ("Jak zamówić?", "Wypełnij formularz imieniem, telefonem i adresem. Nasz zespół skontaktuje się, odpowie na pytania i potwierdzi szczegóły dostawy."),
        ("Czy mogę zapłacić przy odbiorze?", "Tak. Dla wygody i bezpieczeństwa możesz zapłacić przy odbiorze: gdy produkt dotrze, płacisz kurierowi. Dane karty nie są wymagane."),
        ("Czy łatwo latać dla początkujących?", "Tak. Droniq™ jest zaprojektowany dla osób, które nigdy nie latały dronem. Start i lądowanie są automatyczne, sterowanie intuicyjne, a AI pomaga utrzymać stabilny, bezpieczny lot od pierwszego użycia."),
        ("Czy potrzebuję licencji lub certyfikatu?", "Nie. Droniq™ spełnia standard <strong>C0</strong> w kategorii A1/A3 i można go używać bez licencji, certyfikatów ani skomplikowanej papierologii."),
        ("Jaką jakość wideo i zdjęć oferuje?", "Droniq™ nagrywa w <strong>Ultra HD 8K</strong> i robi wyjątkowo ostre zdjęcia. Obiektyw szerokokątny i cyfrowy zoom 22x pozwalają płynnie przejść od panoram do odległych detali."),
        ("Co jeśli dron straci sygnał lub spadnie bateria?", "Dzięki wbudowanemu modułowi GPS Droniq™ automatycznie wraca do punktu startu, jeśli sygnał zostanie utracony lub bateria jest niska."),
        ("Co jeśli nie jestem zadowolony?", "Masz <strong>30 dni</strong> od dostawy na zwrot lub wymianę, plus 24-miesięczną gwarancję na wady produkcyjne i wsparcie klienta."),
        ("Ile kosztuje dostawa i ile trwa?", "Dostawa jest <strong>darmowa</strong>. Zamówienia przetwarzamy w ciągu 24 godzin; kurier zwykle przyjeżdża w 24/48 godzin roboczych."),
    ],
    "footer_blurb": "Przydatne produkty codziennego użytku, dostawa w 24–48 godzin z płatnością przy odbiorze.",
    "footer_info": "Informacje",
    "footer_about": "O nas",
    "footer_contact_us": "Kontakt",
    "footer_privacy": "Polityka prywatności",
    "footer_terms": "Regulamin",
    "footer_cookie": "Polityka cookies",
    "footer_shipping": "Polityka dostawy",
    "footer_refund": "Polityka zwrotów",
    "footer_contact": "Kontakt",
    "footer_rights": "Wszelkie prawa zastrzeżone",
    "ty_title": "Zamówienie otrzymane — Prosimy odebrać telefon potwierdzający | Droniq™",
    "ty_meta": "Twoje zamówienie Droniq™ zostało zarejestrowane. Ostatni krok: odbierz telefon potwierdzający od naszego operatora.",
    "ty_h1": "Twoje zamówienie zostało pomyślnie zarejestrowane!",
    "ty_sub": "Świetnie — Twoje zamówienie jest przetwarzane. Został tylko <strong>jeden ostatni krok</strong>, aby je dokończyć i rozpocząć wysyłkę.",
    "ty_img_alt": "Zespół Crazy Marketing w pracy: call center COD i logistyka",
    "ty_eye": "👇 Co musisz zrobić teraz",
    "ty_action_h": "📞 Odbierz telefon potwierdzający",
    "ty_action_body": "Jeden z naszych operatorów skontaktuje się z Tobą <strong>w ciągu najbliższych godzin</strong>, aby potwierdzić zamówienie.",
    "ty_warn": "Jeśli nie odbierzesz telefonu, zamówienie zostanie automatycznie anulowane.",
    "ty_hours_h": "🕒 Godziny kontaktu",
    "ty_hours": "<strong>Poniedziałek – Sobota</strong> · 9:00 – 18:00",
    "ty_next_h": "📋 Co dalej",
    "ty_s1": "Odbierz telefon i <strong>potwierdź swoje dane</strong>",
    "ty_s2": "Twoje zamówienie zostanie wysłane w ciągu <strong>24–48 godzin</strong>",
    "ty_s3": "Dostawa do domu i <strong>płatność przy odbiorze</strong>",
    "ty_b1": "🔒 Płatność przy odbiorze",
    "ty_b2": "🛡️ 2-letnia gwarancja",
    "ty_b3": "🔐 Ochrona SSL",
    "ty_rights": "Wszelkie prawa zastrzeżone.",
    "index_link": "Przejdź do landingu Droniq™",
}
